# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
    
#     - name: Create and activate virtual environment
#       run: |
#         python -m venv venv  # Create a virtual environment
#         source venv/bin/activate  # Activate the virtual environment

#     - name: Install dependencies in virtual environment
#       run: |
#         source venv/bin/activate  # Activate the virtual environment
#         pip install -r requirements.txt

#     - name: Run Tests
#       run: |
#         source venv/bin/activate  # Activate the virtual environment
#         pytest --disable-warnings

#   terraform-check:
#     runs-on: ubuntu-latest
#     needs: build-and-test

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Terraform
#       uses: hashicorp/setup-terraform@v2
#       with:
#         terraform_version: 1.0.0

#     - name: Initialize and validate Terraform
#       run: |
#         terraform init
#         terraform validate
