name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        # Activate virtual environment if using one
        # If using a virtual environment, you can create and activate it
        python -m venv venv
        # source venv/bin/activate  # For Unix/Linux
        # or for Windows use:
        iac_drift_monitor_env\Scripts\Activate.ps1
        python -m pytest --disable-warnings

  terraform-check:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0

    - name: Initialize and validate Terraform
      run: |
        terraform init
        terraform validate
